users:
  john:
    disabled: false
    displayname: 'John Doe'
    # The password is "password"
    password: '$argon2id$v=19$m=65536,t=3,p=2$BpLnfgDsc2WD8F2q$o/vzA4myCqZZ36bUGsDY//8mKUYNZZaR0t4MFFSs+iM'
    email: 'john.doe@example.org'
    groups:
      - 'admins'
      - 'dev'
