services:
  cms:
    build: .
    container_name: cms
    hostname: ${CMS_DOMAIN}
    expose:
      - 1337
  proxy:
    image: nginx:1.27-alpine
    container_name: proxy
    hostname: ${DOMAIN}
    depends_on:
      - idp
      - cms
    environment:
      - AUTH_DOMAIN
      - CMS_DOMAIN
      - DOMAIN
    ports:
      - "80:80"
      - "443:443"
    restart: "unless-stopped"
    volumes:
      - './config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './config/nginx/snippets:/etc/nginx/snippets:ro'
      - './config/nginx/templates:/etc/nginx/templates:ro'
      - './data/common/certs/fullchain.pem:/config/keys/cert.crt:ro'
      - './data/common/certs/serverkey.pem:/config/keys/cert.key:ro'
  idp:
    image: "authelia/authelia:4.39"
    container_name: idp
    hostname: ${AUTH_DOMAIN}
    environment:
      - AUTH_DOMAIN
      - AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE=/run/secrets/hmac_secret
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE=/run/secrets/jwt_secret
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/auth_session_secret
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/run/secrets/auth_storage_key
      - DOMAIN
      - ORGANIZATION_NAME=Strapi OIDC
      - X_AUTHELIA_CONFIG_FILTERS=template
    expose:
      - 9091
    restart: "unless-stopped"
    secrets:
      - auth_session_secret
      - auth_storage_key
      - hmac_secret
      - jwks_key
      - jwt_secret
      - oidc_strapi_id
      - oidc_strapi_digest
    volumes:
      - ./config/authelia/configuration.yml:/config/configuration.yml:ro
      - ./config/authelia/users.yml:/config/users.yml:ro

secrets:
  auth_session_secret:
    file: ./config/authelia/secrets/session-secret.txt
  auth_storage_key:
    file: ./config/authelia/secrets/storage-key.txt
  hmac_secret:
    file: ./config/authelia/secrets/hmac-secret.txt
  jwks_key:
    file: ./config/authelia/secrets/jwks-key.pem
  jwt_secret:
    file: ./config/authelia/secrets/jwt-secret.txt
  oidc_strapi_id:
    file: ./config/authelia/secrets/clients/strapi_id.txt
  oidc_strapi_digest:
    file: ./config/authelia/secrets/clients/strapi_digest.txt
